// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/dictionaries.dart';
import 'models/inventory_movement_compact.dart';
import 'models/label_print_item_compact.dart';
import 'models/order_compact.dart';
import 'models/product_compact.dart';
import 'models/product_optimized.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5912691597670405774),
      name: 'AttributeDictionary',
      lastPropertyId: const obx_int.IdUid(2, 6940056475542666945),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3115954139413808837),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6940056475542666945),
            name: 'name',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 1300617398608162648))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4570309480777301355),
      name: 'AttributeValueDictionary',
      lastPropertyId: const obx_int.IdUid(3, 4491584961991591856),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3633801262421401323),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6699866966204426063),
            name: 'attributeId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(2, 2875154837274612642)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4491584961991591856),
            name: 'value',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 3283692701494542039),
      name: 'BrandDictionary',
      lastPropertyId: const obx_int.IdUid(3, 2149854359014702575),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 598151212782158800),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5034335944469264942),
            name: 'name',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 1497829615400721701)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2149854359014702575),
            name: 'logoFilename',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 282272680191844775),
      name: 'ProductCompact',
      lastPropertyId: const obx_int.IdUid(16, 2355102336414408036),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6479337330994351250),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8417564712612963457),
            name: 'id',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(4, 7340588239223204340)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5088411780295351133),
            name: 'name',
            type: 9,
            flags: 8,
            indexId: const obx_int.IdUid(5, 190766829234595025)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 235945402663605104),
            name: 'sku',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(6, 3683559838272585560)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 661253156238789262),
            name: 'barcode',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(7, 8918605421421175217)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8095923511186502195),
            name: 'stockQuantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8028350975319162033),
            name: 'brandId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5989482495812450728),
            name: 'hasVariations',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3766642056419868486),
            name: 'imageCached',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1649481634983149761),
            name: 'attributeIds',
            type: 27,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6123067407638516948),
            name: 'variationData',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 5339972116663226110),
            name: 'priceInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 3812630261942067200),
            name: 'stockStatus',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 7522848257548679000),
            name: 'lastUpdated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 983156779819653577),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 2355102336414408036),
            name: 'parentId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 2403171748527253635),
      name: 'ProductOptimized',
      lastPropertyId: const obx_int.IdUid(21, 3052370980980769033),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1847789495228120492),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 610942739332265231),
            name: 'id',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(8, 3342973888849605003)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8037775338160733027),
            name: 'brandId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5698497979141566513),
            name: 'categoryId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6027910048908018873),
            name: 'parentId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4602484254847126589),
            name: 'imageId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8819678551017866256),
            name: 'name',
            type: 9,
            flags: 8,
            indexId: const obx_int.IdUid(9, 8647301190182981791)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7998159653201991967),
            name: 'sku',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(10, 6786610746005392177)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8522813927121149703),
            name: 'barcode',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(11, 8567358356747848779)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7794558745265355400),
            name: 'variantSku',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2019230970905030014),
            name: 'priceInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 2888563291345033650),
            name: 'specialPriceInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 5484131487012448448),
            name: 'stockQuantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 9199078028601581281),
            name: 'attributesCompressed',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2872871277568632785),
            name: 'lastUpdated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 6051185490730777610),
            name: 'productType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 4392235176829616387),
            name: 'stockStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 8337508630725038465),
            name: 'flags',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 3087462947142702588),
            name: 'isOnSale',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 7889725388069201927),
            name: 'isFeatured',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 3052370980980769033),
            name: 'managingStock',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 7967496408929011251),
      name: 'VariationCompact',
      lastPropertyId: const obx_int.IdUid(9, 6433797053234303999),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1070263987926663005),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2881763073094330241),
            name: 'id',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(12, 5939546674042056734)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5365030245349527183),
            name: 'parentId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(13, 7906817654316832526)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 912177928968034079),
            name: 'sku',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 508762125194493734),
            name: 'stockQuantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7789295231457869786),
            name: 'attributeValues',
            type: 27,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3540784373071342265),
            name: 'priceInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7393427885927193024),
            name: 'stockStatus',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6433797053234303999),
            name: 'lastUpdated',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 2596299436059906725),
      name: 'VariationOptimized',
      lastPropertyId: const obx_int.IdUid(11, 1848991102510228506),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6368442348675504511),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6325471414734179057),
            name: 'id',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(14, 1222029337296047992)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7809006332407488975),
            name: 'parentId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(15, 8059606132885089375)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2857485129967528561),
            name: 'skuSuffix',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3587196039985556331),
            name: 'barcode',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(16, 8791303141575024171)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1867499479753941415),
            name: 'stockQuantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2960006547045195910),
            name: 'attributeIds',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4917406165752572787),
            name: 'priceInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8764666461001811434),
            name: 'stockStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7495980997844049416),
            name: 'flags',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1848991102510228506),
            name: 'lastUpdated',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 5136744946607683122),
      name: 'InventoryMovementCompact',
      lastPropertyId: const obx_int.IdUid(10, 7779436138711694452),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4833166999648797010),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8114704434142462849),
            name: 'movementId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(17, 7770405521476093839)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1870794916953695951),
            name: 'userId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4232007268953928143),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2775008039443780939),
            name: 'userName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8433332140828390444),
            name: 'itemsJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 829151921653443606),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6974643351948297174),
            name: 'movementTypeCode',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 566408237070575365),
            name: 'flags',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7779436138711694452),
            name: 'isSynced',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 519634666904773050),
      name: 'LabelPrintItemCompact',
      lastPropertyId: const obx_int.IdUid(15, 1856413454954610522),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2051725587049318385),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9222470961314259680),
            name: 'itemId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(18, 7354957054057740731)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8176477177238225786),
            name: 'productId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(19, 3904071502157395536)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8471120626645642760),
            name: 'variationId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3931656429335412087),
            name: 'productName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7230457029309453979),
            name: 'sku',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2942946726357658950),
            name: 'barcode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4045571572433512483),
            name: 'brand',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7566155353772601033),
            name: 'variantText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4710486492384020737),
            name: 'lotNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2163360670408515664),
            name: 'quantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 2733984003399990269),
            name: 'labelDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 138932702750818830),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4486727482382870286),
            name: 'flags',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 1856413454954610522),
            name: 'isPrinted',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(10, 4948770177190922620),
      name: 'OrderCompact',
      lastPropertyId: const obx_int.IdUid(16, 7390747908456197387),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8838624642040122278),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6130713929815872703),
            name: 'orderId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(20, 4203150918827089401)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 903515474118469024),
            name: 'localOrderId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(21, 6971201470527601049)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1608090882988214276),
            name: 'customerId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2516455582209893543),
            name: 'orderNumber',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(22, 3604040165149682629)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1237909051199702254),
            name: 'customerName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5966543765866165187),
            name: 'itemsJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4240747004786022103),
            name: 'subtotalInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 570737917488277440),
            name: 'taxInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1544311784104793193),
            name: 'discountInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2500345364195545570),
            name: 'totalInCents',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3753796896434368376),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4665286310882555981),
            name: 'orderStatusCode',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 1379993370847648269),
            name: 'flags',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 5495699560597667162),
            name: 'isSynced',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 7390747908456197387),
            name: 'isPaid',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(11, 8037576150524811474),
      name: 'CategoryDictionary',
      lastPropertyId: const obx_int.IdUid(3, 4364925264795627565),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4483010983306660671),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3488189533965093236),
            name: 'name',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(23, 2458770534308670138)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4364925264795627565),
            name: 'slug',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(11, 8037576150524811474),
      lastIndexId: const obx_int.IdUid(23, 2458770534308670138),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AttributeDictionary: obx_int.EntityDefinition<AttributeDictionary>(
        model: _entities[0],
        toOneRelations: (AttributeDictionary object) => [],
        toManyRelations: (AttributeDictionary object) => {},
        getId: (AttributeDictionary object) => object.id,
        setId: (AttributeDictionary object, int id) {
          object.id = id;
        },
        objectToFB: (AttributeDictionary object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = AttributeDictionary(id: idParam, name: nameParam);

          return object;
        }),
    AttributeValueDictionary:
        obx_int.EntityDefinition<AttributeValueDictionary>(
            model: _entities[1],
            toOneRelations: (AttributeValueDictionary object) => [],
            toManyRelations: (AttributeValueDictionary object) => {},
            getId: (AttributeValueDictionary object) => object.id,
            setId: (AttributeValueDictionary object, int id) {
              object.id = id;
            },
            objectToFB: (AttributeValueDictionary object, fb.Builder fbb) {
              final valueOffset = fbb.writeString(object.value);
              fbb.startTable(4);
              fbb.addInt64(0, object.id);
              fbb.addInt64(1, object.attributeId);
              fbb.addOffset(2, valueOffset);
              fbb.finish(fbb.endTable());
              return object.id;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final idParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
              final attributeIdParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
              final valueParam = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
              final object = AttributeValueDictionary(
                  id: idParam,
                  attributeId: attributeIdParam,
                  value: valueParam);

              return object;
            }),
    BrandDictionary: obx_int.EntityDefinition<BrandDictionary>(
        model: _entities[2],
        toOneRelations: (BrandDictionary object) => [],
        toManyRelations: (BrandDictionary object) => {},
        getId: (BrandDictionary object) => object.id,
        setId: (BrandDictionary object, int id) {
          object.id = id;
        },
        objectToFB: (BrandDictionary object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final logoFilenameOffset = object.logoFilename == null
              ? null
              : fbb.writeString(object.logoFilename!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, logoFilenameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final logoFilenameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final object = BrandDictionary(
              id: idParam, name: nameParam, logoFilename: logoFilenameParam);

          return object;
        }),
    ProductCompact: obx_int.EntityDefinition<ProductCompact>(
        model: _entities[3],
        toOneRelations: (ProductCompact object) => [],
        toManyRelations: (ProductCompact object) => {},
        getId: (ProductCompact object) => object.localId,
        setId: (ProductCompact object, int id) {
          object.localId = id;
        },
        objectToFB: (ProductCompact object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final skuOffset =
              object.sku == null ? null : fbb.writeString(object.sku!);
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final attributeIdsOffset = fbb.writeListInt64(object.attributeIds);
          final variationDataOffset = object.variationData == null
              ? null
              : fbb.writeListInt8(object.variationData!);
          final stockStatusOffset = fbb.writeString(object.stockStatus);
          final typeOffset = fbb.writeString(object.type);
          fbb.startTable(17);
          fbb.addInt64(0, object.localId);
          fbb.addInt64(1, object.id);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, skuOffset);
          fbb.addOffset(4, barcodeOffset);
          fbb.addInt64(5, object.stockQuantity);
          fbb.addInt64(6, object.brandId);
          fbb.addBool(7, object.hasVariations);
          fbb.addBool(8, object.imageCached);
          fbb.addOffset(9, attributeIdsOffset);
          fbb.addOffset(10, variationDataOffset);
          fbb.addInt64(11, object.priceInCents);
          fbb.addOffset(12, stockStatusOffset);
          fbb.addInt64(13, object.lastUpdated.millisecondsSinceEpoch);
          fbb.addOffset(14, typeOffset);
          fbb.addInt64(15, object.parentId);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final localIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final skuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final stockQuantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final brandIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final hasVariationsParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final imageCachedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final attributeIdsParam =
              const fb.ListReader<int>(fb.Int64Reader(), lazy: false)
                  .vTableGet(buffer, rootOffset, 22, []);
          final variationDataParam =
              const fb.ListReader<int>(fb.Int8Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final priceInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final stockStatusParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, '');
          final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0));
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 32, '');
          final parentIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34);
          final object = ProductCompact(
              localId: localIdParam,
              id: idParam,
              name: nameParam,
              sku: skuParam,
              barcode: barcodeParam,
              stockQuantity: stockQuantityParam,
              brandId: brandIdParam,
              hasVariations: hasVariationsParam,
              imageCached: imageCachedParam,
              attributeIds: attributeIdsParam,
              variationData: variationDataParam,
              priceInCents: priceInCentsParam,
              stockStatus: stockStatusParam,
              lastUpdated: lastUpdatedParam,
              type: typeParam,
              parentId: parentIdParam);

          return object;
        }),
    ProductOptimized: obx_int.EntityDefinition<ProductOptimized>(
        model: _entities[4],
        toOneRelations: (ProductOptimized object) => [],
        toManyRelations: (ProductOptimized object) => {},
        getId: (ProductOptimized object) => object.localId,
        setId: (ProductOptimized object, int id) {
          object.localId = id;
        },
        objectToFB: (ProductOptimized object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final skuOffset =
              object.sku == null ? null : fbb.writeString(object.sku!);
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final variantSkuOffset = object.variantSku == null
              ? null
              : fbb.writeString(object.variantSku!);
          final attributesCompressedOffset = object.attributesCompressed == null
              ? null
              : fbb.writeListInt8(object.attributesCompressed!);
          fbb.startTable(22);
          fbb.addInt64(0, object.localId);
          fbb.addInt64(1, object.id);
          fbb.addInt64(2, object.brandId);
          fbb.addInt64(3, object.categoryId);
          fbb.addInt64(4, object.parentId);
          fbb.addInt64(5, object.imageId);
          fbb.addOffset(6, nameOffset);
          fbb.addOffset(7, skuOffset);
          fbb.addOffset(8, barcodeOffset);
          fbb.addOffset(9, variantSkuOffset);
          fbb.addInt64(10, object.priceInCents);
          fbb.addInt64(11, object.specialPriceInCents);
          fbb.addInt64(12, object.stockQuantity);
          fbb.addOffset(13, attributesCompressedOffset);
          fbb.addInt64(14, object.lastUpdated.millisecondsSinceEpoch);
          fbb.addInt64(15, object.productType);
          fbb.addInt64(16, object.stockStatus);
          fbb.addInt64(17, object.flags);
          fbb.addBool(18, object.isOnSale);
          fbb.addBool(19, object.isFeatured);
          fbb.addBool(20, object.managingStock);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final brandIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final categoryIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final parentIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final imageIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final skuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final variantSkuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final priceInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final specialPriceInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final stockQuantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final attributesCompressedParam =
              const fb.Uint8ListReader(lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 30) as Uint8List?;
          final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0));
          final productTypeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0);
          final stockStatusParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          final flagsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0);
          final object = ProductOptimized(
              id: idParam,
              brandId: brandIdParam,
              categoryId: categoryIdParam,
              parentId: parentIdParam,
              imageId: imageIdParam,
              name: nameParam,
              sku: skuParam,
              barcode: barcodeParam,
              variantSku: variantSkuParam,
              priceInCents: priceInCentsParam,
              specialPriceInCents: specialPriceInCentsParam,
              stockQuantity: stockQuantityParam,
              attributesCompressed: attributesCompressedParam,
              lastUpdated: lastUpdatedParam,
              productType: productTypeParam,
              stockStatus: stockStatusParam,
              flags: flagsParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..isOnSale =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 40, false)
            ..isFeatured =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 42, false)
            ..managingStock =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 44, false);

          return object;
        }),
    VariationCompact: obx_int.EntityDefinition<VariationCompact>(
        model: _entities[5],
        toOneRelations: (VariationCompact object) => [],
        toManyRelations: (VariationCompact object) => {},
        getId: (VariationCompact object) => object.localId,
        setId: (VariationCompact object, int id) {
          object.localId = id;
        },
        objectToFB: (VariationCompact object, fb.Builder fbb) {
          final skuOffset =
              object.sku == null ? null : fbb.writeString(object.sku!);
          final attributeValuesOffset =
              fbb.writeListInt64(object.attributeValues);
          final stockStatusOffset = fbb.writeString(object.stockStatus);
          fbb.startTable(10);
          fbb.addInt64(0, object.localId);
          fbb.addInt64(1, object.id);
          fbb.addInt64(2, object.parentId);
          fbb.addOffset(3, skuOffset);
          fbb.addInt64(4, object.stockQuantity);
          fbb.addOffset(5, attributeValuesOffset);
          fbb.addInt64(6, object.priceInCents);
          fbb.addOffset(7, stockStatusOffset);
          fbb.addInt64(8, object.lastUpdated.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final localIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final parentIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final skuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final stockQuantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final attributeValuesParam =
              const fb.ListReader<int>(fb.Int64Reader(), lazy: false)
                  .vTableGet(buffer, rootOffset, 14, []);
          final priceInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final stockStatusParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, '');
          final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final object = VariationCompact(
              localId: localIdParam,
              id: idParam,
              parentId: parentIdParam,
              sku: skuParam,
              stockQuantity: stockQuantityParam,
              attributeValues: attributeValuesParam,
              priceInCents: priceInCentsParam,
              stockStatus: stockStatusParam,
              lastUpdated: lastUpdatedParam);

          return object;
        }),
    VariationOptimized: obx_int.EntityDefinition<VariationOptimized>(
        model: _entities[6],
        toOneRelations: (VariationOptimized object) => [],
        toManyRelations: (VariationOptimized object) => {},
        getId: (VariationOptimized object) => object.localId,
        setId: (VariationOptimized object, int id) {
          object.localId = id;
        },
        objectToFB: (VariationOptimized object, fb.Builder fbb) {
          final skuSuffixOffset = object.skuSuffix == null
              ? null
              : fbb.writeString(object.skuSuffix!);
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final attributeIdsOffset = fbb.writeListInt8(object.attributeIds);
          fbb.startTable(12);
          fbb.addInt64(0, object.localId);
          fbb.addInt64(1, object.id);
          fbb.addInt64(2, object.parentId);
          fbb.addOffset(3, skuSuffixOffset);
          fbb.addOffset(4, barcodeOffset);
          fbb.addInt64(5, object.stockQuantity);
          fbb.addOffset(6, attributeIdsOffset);
          fbb.addInt64(7, object.priceInCents);
          fbb.addInt64(8, object.stockStatus);
          fbb.addInt64(9, object.flags);
          fbb.addInt64(10, object.lastUpdated.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final parentIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final skuSuffixParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final stockQuantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final attributeIdsParam = const fb.Uint8ListReader(lazy: false)
              .vTableGet(buffer, rootOffset, 16, Uint8List(0)) as Uint8List;
          final priceInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final stockStatusParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final flagsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0));
          final object = VariationOptimized(
              id: idParam,
              parentId: parentIdParam,
              skuSuffix: skuSuffixParam,
              barcode: barcodeParam,
              stockQuantity: stockQuantityParam,
              attributeIds: attributeIdsParam,
              priceInCents: priceInCentsParam,
              stockStatus: stockStatusParam,
              flags: flagsParam,
              lastUpdated: lastUpdatedParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    InventoryMovementCompact: obx_int.EntityDefinition<
            InventoryMovementCompact>(
        model: _entities[7],
        toOneRelations: (InventoryMovementCompact object) => [],
        toManyRelations: (InventoryMovementCompact object) => {},
        getId: (InventoryMovementCompact object) => object.localId,
        setId: (InventoryMovementCompact object, int id) {
          object.localId = id;
        },
        objectToFB: (InventoryMovementCompact object, fb.Builder fbb) {
          final movementIdOffset = fbb.writeString(object.movementId);
          final descriptionOffset = fbb.writeString(object.description);
          final userNameOffset = fbb.writeString(object.userName);
          final itemsJsonOffset = fbb.writeString(object.itemsJson);
          fbb.startTable(11);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, movementIdOffset);
          fbb.addInt64(2, object.userId);
          fbb.addOffset(3, descriptionOffset);
          fbb.addOffset(4, userNameOffset);
          fbb.addOffset(5, itemsJsonOffset);
          fbb.addInt64(6, object.date.millisecondsSinceEpoch);
          fbb.addInt64(7, object.movementTypeCode);
          fbb.addInt64(8, object.flags);
          fbb.addBool(9, object.isSynced);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final movementIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final userIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final userNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final itemsJsonParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final movementTypeCodeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final flagsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final object = InventoryMovementCompact(
              movementId: movementIdParam,
              userId: userIdParam,
              description: descriptionParam,
              userName: userNameParam,
              itemsJson: itemsJsonParam,
              date: dateParam,
              movementTypeCode: movementTypeCodeParam,
              flags: flagsParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..isSynced =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false);

          return object;
        }),
    LabelPrintItemCompact: obx_int.EntityDefinition<LabelPrintItemCompact>(
        model: _entities[8],
        toOneRelations: (LabelPrintItemCompact object) => [],
        toManyRelations: (LabelPrintItemCompact object) => {},
        getId: (LabelPrintItemCompact object) => object.localId,
        setId: (LabelPrintItemCompact object, int id) {
          object.localId = id;
        },
        objectToFB: (LabelPrintItemCompact object, fb.Builder fbb) {
          final itemIdOffset = fbb.writeString(object.itemId);
          final productNameOffset = fbb.writeString(object.productName);
          final skuOffset = fbb.writeString(object.sku);
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final brandOffset =
              object.brand == null ? null : fbb.writeString(object.brand!);
          final variantTextOffset = object.variantText == null
              ? null
              : fbb.writeString(object.variantText!);
          final lotNumberOffset = object.lotNumber == null
              ? null
              : fbb.writeString(object.lotNumber!);
          fbb.startTable(16);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, itemIdOffset);
          fbb.addInt64(2, object.productId);
          fbb.addInt64(3, object.variationId);
          fbb.addOffset(4, productNameOffset);
          fbb.addOffset(5, skuOffset);
          fbb.addOffset(6, barcodeOffset);
          fbb.addOffset(7, brandOffset);
          fbb.addOffset(8, variantTextOffset);
          fbb.addOffset(9, lotNumberOffset);
          fbb.addInt64(10, object.quantity);
          fbb.addInt64(11, object.labelDate?.millisecondsSinceEpoch);
          fbb.addInt64(12, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(13, object.flags);
          fbb.addBool(14, object.isPrinted);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final labelDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26);
          final itemIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final productIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final variationIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final productNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final skuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final brandParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final variantTextParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final lotNumberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final quantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final labelDateParam = labelDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(labelDateValue);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0));
          final flagsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          final object = LabelPrintItemCompact(
              itemId: itemIdParam,
              productId: productIdParam,
              variationId: variationIdParam,
              productName: productNameParam,
              sku: skuParam,
              barcode: barcodeParam,
              brand: brandParam,
              variantText: variantTextParam,
              lotNumber: lotNumberParam,
              quantity: quantityParam,
              labelDate: labelDateParam,
              createdAt: createdAtParam,
              flags: flagsParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..isPrinted =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false);

          return object;
        }),
    OrderCompact: obx_int.EntityDefinition<OrderCompact>(
        model: _entities[9],
        toOneRelations: (OrderCompact object) => [],
        toManyRelations: (OrderCompact object) => {},
        getId: (OrderCompact object) => object.localId,
        setId: (OrderCompact object, int id) {
          object.localId = id;
        },
        objectToFB: (OrderCompact object, fb.Builder fbb) {
          final localOrderIdOffset = fbb.writeString(object.localOrderId);
          final orderNumberOffset = object.orderNumber == null
              ? null
              : fbb.writeString(object.orderNumber!);
          final customerNameOffset = fbb.writeString(object.customerName);
          final itemsJsonOffset = fbb.writeString(object.itemsJson);
          fbb.startTable(17);
          fbb.addInt64(0, object.localId);
          fbb.addInt64(1, object.orderId);
          fbb.addOffset(2, localOrderIdOffset);
          fbb.addInt64(3, object.customerId);
          fbb.addOffset(4, orderNumberOffset);
          fbb.addOffset(5, customerNameOffset);
          fbb.addOffset(6, itemsJsonOffset);
          fbb.addInt64(7, object.subtotalInCents);
          fbb.addInt64(8, object.taxInCents);
          fbb.addInt64(9, object.discountInCents);
          fbb.addInt64(10, object.totalInCents);
          fbb.addInt64(11, object.date.millisecondsSinceEpoch);
          fbb.addInt64(12, object.orderStatusCode);
          fbb.addInt64(13, object.flags);
          fbb.addBool(14, object.isSynced);
          fbb.addBool(15, object.isPaid);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final localOrderIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final orderIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final customerIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final orderNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final customerNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final itemsJsonParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final subtotalInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final taxInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final discountInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final totalInCentsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0));
          final orderStatusCodeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final flagsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          final object = OrderCompact(
              localOrderId: localOrderIdParam,
              orderId: orderIdParam,
              customerId: customerIdParam,
              orderNumber: orderNumberParam,
              customerName: customerNameParam,
              itemsJson: itemsJsonParam,
              subtotalInCents: subtotalInCentsParam,
              taxInCents: taxInCentsParam,
              discountInCents: discountInCentsParam,
              totalInCents: totalInCentsParam,
              date: dateParam,
              orderStatusCode: orderStatusCodeParam,
              flags: flagsParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..isSynced =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false)
            ..isPaid =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 34, false);

          return object;
        }),
    CategoryDictionary: obx_int.EntityDefinition<CategoryDictionary>(
        model: _entities[10],
        toOneRelations: (CategoryDictionary object) => [],
        toManyRelations: (CategoryDictionary object) => {},
        getId: (CategoryDictionary object) => object.id,
        setId: (CategoryDictionary object, int id) {
          object.id = id;
        },
        objectToFB: (CategoryDictionary object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final slugOffset =
              object.slug == null ? null : fbb.writeString(object.slug!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, slugOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final slugParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final object =
              CategoryDictionary(id: idParam, name: nameParam, slug: slugParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AttributeDictionary] entity fields to define ObjectBox queries.
class AttributeDictionary_ {
  /// See [AttributeDictionary.id].
  static final id =
      obx.QueryIntegerProperty<AttributeDictionary>(_entities[0].properties[0]);

  /// See [AttributeDictionary.name].
  static final name =
      obx.QueryStringProperty<AttributeDictionary>(_entities[0].properties[1]);
}

/// [AttributeValueDictionary] entity fields to define ObjectBox queries.
class AttributeValueDictionary_ {
  /// See [AttributeValueDictionary.id].
  static final id = obx.QueryIntegerProperty<AttributeValueDictionary>(
      _entities[1].properties[0]);

  /// See [AttributeValueDictionary.attributeId].
  static final attributeId = obx.QueryIntegerProperty<AttributeValueDictionary>(
      _entities[1].properties[1]);

  /// See [AttributeValueDictionary.value].
  static final value = obx.QueryStringProperty<AttributeValueDictionary>(
      _entities[1].properties[2]);
}

/// [BrandDictionary] entity fields to define ObjectBox queries.
class BrandDictionary_ {
  /// See [BrandDictionary.id].
  static final id =
      obx.QueryIntegerProperty<BrandDictionary>(_entities[2].properties[0]);

  /// See [BrandDictionary.name].
  static final name =
      obx.QueryStringProperty<BrandDictionary>(_entities[2].properties[1]);

  /// See [BrandDictionary.logoFilename].
  static final logoFilename =
      obx.QueryStringProperty<BrandDictionary>(_entities[2].properties[2]);
}

/// [ProductCompact] entity fields to define ObjectBox queries.
class ProductCompact_ {
  /// See [ProductCompact.localId].
  static final localId =
      obx.QueryIntegerProperty<ProductCompact>(_entities[3].properties[0]);

  /// See [ProductCompact.id].
  static final id =
      obx.QueryIntegerProperty<ProductCompact>(_entities[3].properties[1]);

  /// See [ProductCompact.name].
  static final name =
      obx.QueryStringProperty<ProductCompact>(_entities[3].properties[2]);

  /// See [ProductCompact.sku].
  static final sku =
      obx.QueryStringProperty<ProductCompact>(_entities[3].properties[3]);

  /// See [ProductCompact.barcode].
  static final barcode =
      obx.QueryStringProperty<ProductCompact>(_entities[3].properties[4]);

  /// See [ProductCompact.stockQuantity].
  static final stockQuantity =
      obx.QueryIntegerProperty<ProductCompact>(_entities[3].properties[5]);

  /// See [ProductCompact.brandId].
  static final brandId =
      obx.QueryIntegerProperty<ProductCompact>(_entities[3].properties[6]);

  /// See [ProductCompact.hasVariations].
  static final hasVariations =
      obx.QueryBooleanProperty<ProductCompact>(_entities[3].properties[7]);

  /// See [ProductCompact.imageCached].
  static final imageCached =
      obx.QueryBooleanProperty<ProductCompact>(_entities[3].properties[8]);

  /// See [ProductCompact.attributeIds].
  static final attributeIds = obx.QueryIntegerVectorProperty<ProductCompact>(
      _entities[3].properties[9]);

  /// See [ProductCompact.variationData].
  static final variationData =
      obx.QueryByteVectorProperty<ProductCompact>(_entities[3].properties[10]);

  /// See [ProductCompact.priceInCents].
  static final priceInCents =
      obx.QueryIntegerProperty<ProductCompact>(_entities[3].properties[11]);

  /// See [ProductCompact.stockStatus].
  static final stockStatus =
      obx.QueryStringProperty<ProductCompact>(_entities[3].properties[12]);

  /// See [ProductCompact.lastUpdated].
  static final lastUpdated =
      obx.QueryDateProperty<ProductCompact>(_entities[3].properties[13]);

  /// See [ProductCompact.type].
  static final type =
      obx.QueryStringProperty<ProductCompact>(_entities[3].properties[14]);

  /// See [ProductCompact.parentId].
  static final parentId =
      obx.QueryIntegerProperty<ProductCompact>(_entities[3].properties[15]);
}

/// [ProductOptimized] entity fields to define ObjectBox queries.
class ProductOptimized_ {
  /// See [ProductOptimized.localId].
  static final localId =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[0]);

  /// See [ProductOptimized.id].
  static final id =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[1]);

  /// See [ProductOptimized.brandId].
  static final brandId =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[2]);

  /// See [ProductOptimized.categoryId].
  static final categoryId =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[3]);

  /// See [ProductOptimized.parentId].
  static final parentId =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[4]);

  /// See [ProductOptimized.imageId].
  static final imageId =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[5]);

  /// See [ProductOptimized.name].
  static final name =
      obx.QueryStringProperty<ProductOptimized>(_entities[4].properties[6]);

  /// See [ProductOptimized.sku].
  static final sku =
      obx.QueryStringProperty<ProductOptimized>(_entities[4].properties[7]);

  /// See [ProductOptimized.barcode].
  static final barcode =
      obx.QueryStringProperty<ProductOptimized>(_entities[4].properties[8]);

  /// See [ProductOptimized.variantSku].
  static final variantSku =
      obx.QueryStringProperty<ProductOptimized>(_entities[4].properties[9]);

  /// See [ProductOptimized.priceInCents].
  static final priceInCents =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[10]);

  /// See [ProductOptimized.specialPriceInCents].
  static final specialPriceInCents =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[11]);

  /// See [ProductOptimized.stockQuantity].
  static final stockQuantity =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[12]);

  /// See [ProductOptimized.attributesCompressed].
  static final attributesCompressed =
      obx.QueryByteVectorProperty<ProductOptimized>(
          _entities[4].properties[13]);

  /// See [ProductOptimized.lastUpdated].
  static final lastUpdated =
      obx.QueryDateProperty<ProductOptimized>(_entities[4].properties[14]);

  /// See [ProductOptimized.productType].
  static final productType =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[15]);

  /// See [ProductOptimized.stockStatus].
  static final stockStatus =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[16]);

  /// See [ProductOptimized.flags].
  static final flags =
      obx.QueryIntegerProperty<ProductOptimized>(_entities[4].properties[17]);

  /// See [ProductOptimized.isOnSale].
  static final isOnSale =
      obx.QueryBooleanProperty<ProductOptimized>(_entities[4].properties[18]);

  /// See [ProductOptimized.isFeatured].
  static final isFeatured =
      obx.QueryBooleanProperty<ProductOptimized>(_entities[4].properties[19]);

  /// See [ProductOptimized.managingStock].
  static final managingStock =
      obx.QueryBooleanProperty<ProductOptimized>(_entities[4].properties[20]);
}

/// [VariationCompact] entity fields to define ObjectBox queries.
class VariationCompact_ {
  /// See [VariationCompact.localId].
  static final localId =
      obx.QueryIntegerProperty<VariationCompact>(_entities[5].properties[0]);

  /// See [VariationCompact.id].
  static final id =
      obx.QueryIntegerProperty<VariationCompact>(_entities[5].properties[1]);

  /// See [VariationCompact.parentId].
  static final parentId =
      obx.QueryIntegerProperty<VariationCompact>(_entities[5].properties[2]);

  /// See [VariationCompact.sku].
  static final sku =
      obx.QueryStringProperty<VariationCompact>(_entities[5].properties[3]);

  /// See [VariationCompact.stockQuantity].
  static final stockQuantity =
      obx.QueryIntegerProperty<VariationCompact>(_entities[5].properties[4]);

  /// See [VariationCompact.attributeValues].
  static final attributeValues =
      obx.QueryIntegerVectorProperty<VariationCompact>(
          _entities[5].properties[5]);

  /// See [VariationCompact.priceInCents].
  static final priceInCents =
      obx.QueryIntegerProperty<VariationCompact>(_entities[5].properties[6]);

  /// See [VariationCompact.stockStatus].
  static final stockStatus =
      obx.QueryStringProperty<VariationCompact>(_entities[5].properties[7]);

  /// See [VariationCompact.lastUpdated].
  static final lastUpdated =
      obx.QueryDateProperty<VariationCompact>(_entities[5].properties[8]);
}

/// [VariationOptimized] entity fields to define ObjectBox queries.
class VariationOptimized_ {
  /// See [VariationOptimized.localId].
  static final localId =
      obx.QueryIntegerProperty<VariationOptimized>(_entities[6].properties[0]);

  /// See [VariationOptimized.id].
  static final id =
      obx.QueryIntegerProperty<VariationOptimized>(_entities[6].properties[1]);

  /// See [VariationOptimized.parentId].
  static final parentId =
      obx.QueryIntegerProperty<VariationOptimized>(_entities[6].properties[2]);

  /// See [VariationOptimized.skuSuffix].
  static final skuSuffix =
      obx.QueryStringProperty<VariationOptimized>(_entities[6].properties[3]);

  /// See [VariationOptimized.barcode].
  static final barcode =
      obx.QueryStringProperty<VariationOptimized>(_entities[6].properties[4]);

  /// See [VariationOptimized.stockQuantity].
  static final stockQuantity =
      obx.QueryIntegerProperty<VariationOptimized>(_entities[6].properties[5]);

  /// See [VariationOptimized.attributeIds].
  static final attributeIds = obx.QueryByteVectorProperty<VariationOptimized>(
      _entities[6].properties[6]);

  /// See [VariationOptimized.priceInCents].
  static final priceInCents =
      obx.QueryIntegerProperty<VariationOptimized>(_entities[6].properties[7]);

  /// See [VariationOptimized.stockStatus].
  static final stockStatus =
      obx.QueryIntegerProperty<VariationOptimized>(_entities[6].properties[8]);

  /// See [VariationOptimized.flags].
  static final flags =
      obx.QueryIntegerProperty<VariationOptimized>(_entities[6].properties[9]);

  /// See [VariationOptimized.lastUpdated].
  static final lastUpdated =
      obx.QueryDateProperty<VariationOptimized>(_entities[6].properties[10]);
}

/// [InventoryMovementCompact] entity fields to define ObjectBox queries.
class InventoryMovementCompact_ {
  /// See [InventoryMovementCompact.localId].
  static final localId = obx.QueryIntegerProperty<InventoryMovementCompact>(
      _entities[7].properties[0]);

  /// See [InventoryMovementCompact.movementId].
  static final movementId = obx.QueryStringProperty<InventoryMovementCompact>(
      _entities[7].properties[1]);

  /// See [InventoryMovementCompact.userId].
  static final userId = obx.QueryIntegerProperty<InventoryMovementCompact>(
      _entities[7].properties[2]);

  /// See [InventoryMovementCompact.description].
  static final description = obx.QueryStringProperty<InventoryMovementCompact>(
      _entities[7].properties[3]);

  /// See [InventoryMovementCompact.userName].
  static final userName = obx.QueryStringProperty<InventoryMovementCompact>(
      _entities[7].properties[4]);

  /// See [InventoryMovementCompact.itemsJson].
  static final itemsJson = obx.QueryStringProperty<InventoryMovementCompact>(
      _entities[7].properties[5]);

  /// See [InventoryMovementCompact.date].
  static final date = obx.QueryDateProperty<InventoryMovementCompact>(
      _entities[7].properties[6]);

  /// See [InventoryMovementCompact.movementTypeCode].
  static final movementTypeCode =
      obx.QueryIntegerProperty<InventoryMovementCompact>(
          _entities[7].properties[7]);

  /// See [InventoryMovementCompact.flags].
  static final flags = obx.QueryIntegerProperty<InventoryMovementCompact>(
      _entities[7].properties[8]);

  /// See [InventoryMovementCompact.isSynced].
  static final isSynced = obx.QueryBooleanProperty<InventoryMovementCompact>(
      _entities[7].properties[9]);
}

/// [LabelPrintItemCompact] entity fields to define ObjectBox queries.
class LabelPrintItemCompact_ {
  /// See [LabelPrintItemCompact.localId].
  static final localId = obx.QueryIntegerProperty<LabelPrintItemCompact>(
      _entities[8].properties[0]);

  /// See [LabelPrintItemCompact.itemId].
  static final itemId = obx.QueryStringProperty<LabelPrintItemCompact>(
      _entities[8].properties[1]);

  /// See [LabelPrintItemCompact.productId].
  static final productId = obx.QueryIntegerProperty<LabelPrintItemCompact>(
      _entities[8].properties[2]);

  /// See [LabelPrintItemCompact.variationId].
  static final variationId = obx.QueryIntegerProperty<LabelPrintItemCompact>(
      _entities[8].properties[3]);

  /// See [LabelPrintItemCompact.productName].
  static final productName = obx.QueryStringProperty<LabelPrintItemCompact>(
      _entities[8].properties[4]);

  /// See [LabelPrintItemCompact.sku].
  static final sku = obx.QueryStringProperty<LabelPrintItemCompact>(
      _entities[8].properties[5]);

  /// See [LabelPrintItemCompact.barcode].
  static final barcode = obx.QueryStringProperty<LabelPrintItemCompact>(
      _entities[8].properties[6]);

  /// See [LabelPrintItemCompact.brand].
  static final brand = obx.QueryStringProperty<LabelPrintItemCompact>(
      _entities[8].properties[7]);

  /// See [LabelPrintItemCompact.variantText].
  static final variantText = obx.QueryStringProperty<LabelPrintItemCompact>(
      _entities[8].properties[8]);

  /// See [LabelPrintItemCompact.lotNumber].
  static final lotNumber = obx.QueryStringProperty<LabelPrintItemCompact>(
      _entities[8].properties[9]);

  /// See [LabelPrintItemCompact.quantity].
  static final quantity = obx.QueryIntegerProperty<LabelPrintItemCompact>(
      _entities[8].properties[10]);

  /// See [LabelPrintItemCompact.labelDate].
  static final labelDate =
      obx.QueryDateProperty<LabelPrintItemCompact>(_entities[8].properties[11]);

  /// See [LabelPrintItemCompact.createdAt].
  static final createdAt =
      obx.QueryDateProperty<LabelPrintItemCompact>(_entities[8].properties[12]);

  /// See [LabelPrintItemCompact.flags].
  static final flags = obx.QueryIntegerProperty<LabelPrintItemCompact>(
      _entities[8].properties[13]);

  /// See [LabelPrintItemCompact.isPrinted].
  static final isPrinted = obx.QueryBooleanProperty<LabelPrintItemCompact>(
      _entities[8].properties[14]);
}

/// [OrderCompact] entity fields to define ObjectBox queries.
class OrderCompact_ {
  /// See [OrderCompact.localId].
  static final localId =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[0]);

  /// See [OrderCompact.orderId].
  static final orderId =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[1]);

  /// See [OrderCompact.localOrderId].
  static final localOrderId =
      obx.QueryStringProperty<OrderCompact>(_entities[9].properties[2]);

  /// See [OrderCompact.customerId].
  static final customerId =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[3]);

  /// See [OrderCompact.orderNumber].
  static final orderNumber =
      obx.QueryStringProperty<OrderCompact>(_entities[9].properties[4]);

  /// See [OrderCompact.customerName].
  static final customerName =
      obx.QueryStringProperty<OrderCompact>(_entities[9].properties[5]);

  /// See [OrderCompact.itemsJson].
  static final itemsJson =
      obx.QueryStringProperty<OrderCompact>(_entities[9].properties[6]);

  /// See [OrderCompact.subtotalInCents].
  static final subtotalInCents =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[7]);

  /// See [OrderCompact.taxInCents].
  static final taxInCents =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[8]);

  /// See [OrderCompact.discountInCents].
  static final discountInCents =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[9]);

  /// See [OrderCompact.totalInCents].
  static final totalInCents =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[10]);

  /// See [OrderCompact.date].
  static final date =
      obx.QueryDateProperty<OrderCompact>(_entities[9].properties[11]);

  /// See [OrderCompact.orderStatusCode].
  static final orderStatusCode =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[12]);

  /// See [OrderCompact.flags].
  static final flags =
      obx.QueryIntegerProperty<OrderCompact>(_entities[9].properties[13]);

  /// See [OrderCompact.isSynced].
  static final isSynced =
      obx.QueryBooleanProperty<OrderCompact>(_entities[9].properties[14]);

  /// See [OrderCompact.isPaid].
  static final isPaid =
      obx.QueryBooleanProperty<OrderCompact>(_entities[9].properties[15]);
}

/// [CategoryDictionary] entity fields to define ObjectBox queries.
class CategoryDictionary_ {
  /// See [CategoryDictionary.id].
  static final id =
      obx.QueryIntegerProperty<CategoryDictionary>(_entities[10].properties[0]);

  /// See [CategoryDictionary.name].
  static final name =
      obx.QueryStringProperty<CategoryDictionary>(_entities[10].properties[1]);

  /// See [CategoryDictionary.slug].
  static final slug =
      obx.QueryStringProperty<CategoryDictionary>(_entities[10].properties[2]);
}
