name: my_pos_mobile_barcode
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  lucide_icons: ^0.257.0
  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  dio: ^5.9.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  flutter_typeahead: ^5.2.0
  lottie: ^3.3.1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_contacts: ^1.1.9+2
  fluttertoast: ^8.2.12
  collection: ^1.19.1
  image_picker: ^1.1.2
  path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  flutter_slidable: ^4.0.0
  package_info_plus: ^8.3.0
  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4
  image: ^4.5.4
  screenshot: ^3.0.0
  file_picker: ^10.3.3
  csv: ^6.0.0
  share_plus: ^12.0.0
  flutter_background_service: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700